name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.14"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SWIG for Windows
        if: runner.os == 'Windows'
        run: choco install -y swig

      - name: Install SWIG for Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y swig

      - name: Install SWIG for macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install swig

      - name: Upgrade build tools
        run: python -m pip install -U pip setuptools wheel

      - name: Install
        run: python -m pip install -v .

      - name: Install test deps
        run: python -m pip install -U pytest coverage pytest-benchmark pytest-mock

      - name: Test
        run: pytest -q
